## Задание на повторение материала

In [1]:
import numpy as np
import numpy.linalg as la

1. Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно

In [2]:
a = np.arange(12, 24)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

2. Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.

In [3]:
a_2x6 = a.reshape(2, 6)
a_3x4 = a.reshape(3, 4)
a_4x3 = a.reshape(4, 3)
a_6x2 = a.reshape(6, 2)
a_12x1 = a.reshape(12, 1)
a_2x6, a_3x4, a_4x3, a_6x2, a_12x1

(array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]),
 array([[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]),
 array([[12, 13],
        [14, 15],
        [16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]),
 array([[12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20],
        [21],
        [22],
        [23]]))

3. Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трёх примерах - для обозначения числа столбцов, в двух - для строк).

In [4]:
a_2xN = a.reshape(2, -1)
a_3xN = a.reshape(3, -1)
a_4xN = a.reshape(4, -1)
a_Nx2 = a.reshape(-1, 2)
a_Nx1 = a.reshape(-1, 1)
a_2xN, a_3xN, a_4xN, a_Nx2, a_Nx1

(array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]),
 array([[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]),
 array([[12, 13],
        [14, 15],
        [16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]),
 array([[12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20],
        [21],
        [22],
        [23]]))

4. Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?

*Нельзя.  
В одномерном массиве прямой доступ к элементу осуществляется с помощью одного индекса.  
При обращении к массиву Numpy из 1 столбца и 12 строк с помощью одного индекса возвращается не сам элемент, а массив из одного элемента.*

In [5]:
print(f"{a[0]}\t{type(a[0])}\n{a_12x1[0]}\t{type(a_12x1[0])}")

12	<class 'numpy.int32'>
[12]	<class 'numpy.ndarray'>


5. Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

In [6]:
rnd_3x4 = np.random.randn(3, 4)
rnd_new = rnd_3x4.flatten()
assert(rnd_3x4.size == rnd_new.size)
rnd_3x4, rnd_new

(array([[ 2.01496541, -0.07885585, -1.01236036, -1.17100712],
        [ 0.34090062,  1.55097829, -0.4772052 , -0.75692118],
        [ 0.97933693,  1.37454227, -0.57092814,  0.72035785]]),
 array([ 2.01496541, -0.07885585, -1.01236036, -1.17100712,  0.34090062,
         1.55097829, -0.4772052 , -0.75692118,  0.97933693,  1.37454227,
        -0.57092814,  0.72035785]))

6. Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.

In [7]:
a = np.arange(20, 0, -2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

7. Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2.

In [8]:
b = np.arange(20, 1, -2).reshape(1, 10)
b

array([[20, 18, 16, 14, 12, 10,  8,  6,  4,  2]])

В чём разница между массивами a и b?  
*Массив a - одномерный, а массив b - двумерный:*

In [9]:
a.shape, b.shape

((10,), (1, 10))

8. Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.

In [10]:
arows = 2
brows = 3
cols = 2
assert((arows > 1) & (arows == (brows - 1)))
a = np.zeros((arows, cols))
b = np.ones((brows, cols))
v = np.vstack((a, b))
assert(v.size == 10)
a, b, v

(array([[0., 0.],
        [0., 0.]]),
 array([[1., 1.],
        [1., 1.],
        [1., 1.]]),
 array([[0., 0.],
        [0., 0.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]))

9. Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения.

In [11]:
a = np.arange(0, 12)
A = a.reshape(4, 3)
At = A.T
B = A @ At
a, A, At, B

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]),
 array([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]]),
 array([[ 0,  3,  6,  9],
        [ 1,  4,  7, 10],
        [ 2,  5,  8, 11]]),
 array([[  5,  14,  23,  32],
        [ 14,  50,  86, 122],
        [ 23,  86, 149, 212],
        [ 32, 122, 212, 302]]))

Какой размер имеет матрица B?

In [12]:
B.shape, B.size

((4, 4), 16)

Получится ли вычислить обратную матрицу для матрицы B и почему?

In [13]:
cnd1 = (B.shape[0] == B.shape[1])
cnd2 = (la.det(B) != 0)
print("Матрица В {} и определитель матрицы B {} нулю => обратная матрица для матрицы B {}".format(
    "квадратная" if cnd1 else "неквадратная",
    "не равен" if cnd2 else "равен",
    "существует" if (cnd1 and cnd2) else "не существует"))

Матрица В квадратная и определитель матрицы B равен нулю => обратная матрица для матрицы B не существует


10. Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.

In [14]:
np.random.seed(42)

11. Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределённых целых чисел от 0 до 16 невключительно.

In [15]:
c = np.random.randint(0, 16, 16)
c

array([ 6,  3, 12, 14, 10,  7, 12,  4,  6,  9,  2,  6, 10, 10,  7,  4])

12. Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.

In [16]:
N = int(np.sqrt(c.size))
C = c.reshape(N, N)
D = C*10 + B
D_det = la.det(D)
D_rank = la.matrix_rank(D)
D_inv = la.inv(D)
C, D, D_det, D_rank, D_inv

(array([[ 6,  3, 12, 14],
        [10,  7, 12,  4],
        [ 6,  9,  2,  6],
        [10, 10,  7,  4]]),
 array([[ 65,  44, 143, 172],
        [114, 120, 206, 162],
        [ 83, 176, 169, 272],
        [132, 222, 282, 342]]),
 -28511999.999999944,
 4,
 array([[ 0.00935396,  0.04486532,  0.05897517, -0.07286055],
        [-0.01503577, -0.00122896, -0.00192971,  0.00967873],
        [-0.00356692, -0.01782828, -0.04152146,  0.04326178],
        [ 0.00909091, -0.00181818,  0.01272727, -0.01090909]]))

13. Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались только нули и единицы. С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4.  Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.

In [17]:
D_inv[D_inv < 0] = 0
D_inv[D_inv > 0] = 1
assert(np.all((D_inv < 0) == (D_inv > 1)))
E = np.where(D_inv, B, C)
D_inv, E

(array([[1., 1., 1., 0.],
        [0., 0., 0., 1.],
        [0., 0., 0., 1.],
        [1., 0., 1., 0.]]),
 array([[  5,  14,  23,  14],
        [ 10,   7,  12, 122],
        [  6,   9,   2, 212],
        [ 32,  10, 212,   4]]))